# Common Labels
labels:
  app: "payments-ui"
  group: "web"

namespace: egov    

# Ingress Configs
ingress:
  enabled: true
  context: "payments-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "payments-ui"
  tag: "console-impel-payment-1d0f3ab65f-81"
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/payments-ui/"
  readinessProbePath: "/payments-ui/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: payments-ui-js-injection
extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf