# Common Labels
labels:
  app: "pgadmin"
namespace: playground

# Ingress Configs
ingress:
  enabled: true
  context: "pgadmin"
  additionalAnnotations: |
    nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header X-Script-Name /pgadmin;

# Init Containers Configs
initContainers: {}

imagePullSecrets:
  name: rate-limit-secret

# Container Configs
image:
  repository: "pgadmin"
  tag: "v4.1.1"
replicas: "1"
httpPort: 8080
serverBasePath: "/pgadmin"
dbUrl: "azure-togo-uat-server.postgres.database.azure.com"
environment: "UAT"
maintenance-db-name: "postgres"           

# Additional Container Envs
env: |  
  - name: SERVER_HOST
    value: {{ .Values.dbUrl | quote }}     
  - name: SERVER_PORT
    value: "5432" 
  - name: SERVER_MODE
    value: "False"         
  - name: SERVER_NAME
    value: {{ .Values.environment | quote }}                 
  - name: MAINTENANCE_DB_NAME
    value: {{ index .Values "maintenance-db-name" | quote }}               
  - name: PGADMIN_PORT
    value: {{ .Values.httpPort | quote }}
  - name: SCRIPT_NAME
    value: {{ .Values.serverBasePath | quote }} 
  - name: PGADMIN_DEFAULT_EMAIL
    valueFrom:
      secretKeyRef:
        key: admin-email
        name: pgadmin
  - name: PGADMIN_DEFAULT_PASSWORD
    valueFrom:
      secretKeyRef:
        key: admin-password
        name: pgadmin
  - name: PGADMIN_READ_EMAIL
    valueFrom:
      secretKeyRef:
        key: read-email
        name: pgadmin
  - name: PGADMIN_READ_PASSWORD
    valueFrom:
      secretKeyRef:
        key: read-password
        name: pgadmin